index:
    path: /
    controller: App\Controller\DefaultController::index

login:
    path: /login
    controller: App\Controller\DefaultController::login

inscription:
    path: /inscription
    controller: App\Controller\DefaultController::inscription

devenir_adherent:
    path: /adherent/{id}
    controller: App\Controller\ActionController::devenirAdherent

trajets:
    path: /trajets
    controller: App\Controller\DefaultController::trajets

loginAction:
    path: /loginSubmit
    controller: App\Controller\ActionController::loginSubmit

inscriptionAction:
    path: /inscriptionSubmit
    controller: App\Controller\ActionController::inscriptionSubmit
