index:
    path: /
    controller: App\Controller\DefaultController::index

login:
    path: /login
    controller: App\Controller\DefaultController::login

inscription:
    path: /inscription
    controller: App\Controller\DefaultController::inscription

loginAction:
    path: /loginSubmit
    controller: App\Controller\ActionController::loginSubmit

inscriptionAction:
    path: /inscriptionSubmit
    controller: App\Controller\ActionController::inscriptionSubmit