index:
    path: /
    controller: App\Controller\DefaultController::index

login:
    path: /login
    controller: App\Controller\DefaultController::login

inscription:
    path: /inscription
    controller: App\Controller\DefaultController::inscription

loginAction:
    path: /login
    controller: App\Controller\DefaultController::login

inscriptionAction:
    path: /inscription
    controller: App\Controller\DefaultController::inscription